'use client'
import {useEffect,useState} from "react";
import {Plus,Trash2,Save,ArrowLeft,LogOut} from "lucide-react";
type Product={id:string;name:string;category:string;price:string;image:string;tag:string;description:string};
const seed:Product[]=[
{id:"1",name:"Premium Paddy Seeds",category:"Seeds",price:"₹480 / pack",image:"https://images.unsplash.com/photo-1536633075091-8d3d1d3d1f1c?auto=format&fit=crop&w=900&q=80",tag:"Best Seller",description:"Quality paddy seeds for productive cultivation."},
{id:"2",name:"Organic Vegetable Seeds",category:"Seeds",price:"₹220 / pack",image:"https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=900&q=80",tag:"Organic",description:"Vegetable seed collection for farms."},
{id:"3",name:"Neem Bio Fertilizer",category:"Fertilizers",price:"₹690 / 5 kg",image:"https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=900&q=80",tag:"Eco Choice",description:"Neem-based farm input for soil and plant nutrition."},
{id:"4",name:"Drip Irrigation Kit",category:"Irrigation",price:"₹1,899 / kit",image:"https://images.unsplash.com/photo-1586771107445-d3ca888129ce?auto=format&fit=crop&w=900&q=80",tag:"Water Smart",description:"Efficient irrigation kit for farms."}];
const KEY="agri-products-v2";
const cats=["Seeds","Fertilizers","Pesticides","Irrigation","Farm Equipment","Tools","Machinery","Sensors & IoT","Organic Inputs"];
export default function Admin(){const[ok,setOk]=useState(false),[pw,setPw]=useState(""),[items,setItems]=useState<Product[]>([]),[edit,setEdit]=useState<Product|null>(null);
useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem(KEY)||"null")||seed)}catch{setItems(seed)}},[]);
const save=(x:Product[])=>{setItems(x);localStorage.setItem(KEY,JSON.stringify(x))};
if(!ok)return <main className="admin-login"><div><div className="admin-logo">🌱</div><h1>Agri Admin</h1><p>Manage vegetables, seeds, equipment, machinery and all marketplace products.</p><input type="password" placeholder="Admin password" value={pw} onChange={e=>setPw(e.target.value)}/><button onClick={()=>pw==="admin123"&&setOk(true)}>Enter Dashboard</button><small>Demo password: admin123. Use real authentication before production.</small><a href="/">← Back to website</a></div></main>;
return <main className="admin-shell"><header className="admin-header"><b>🌱 AGRI ADMIN</b><nav><a href="/"><ArrowLeft size={15}/> Website</a><button onClick={()=>setOk(false)}><LogOut size={15}/> Logout</button></nav></header><section className="admin-main"><div className="admin-title"><div><span>CATALOGUE MANAGEMENT</span><h1>Products & Equipment</h1><p>Anything you add here appears in the marketplace on this browser.</p></div><button onClick={()=>setEdit({id:crypto.randomUUID(),name:"New Product",category:"Farm Equipment",price:"₹0",image:"https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=900&q=80",tag:"New",description:"Product description"})}><Plus size={17}/> Add product</button></div><div className="admin-grid">{items.map(x=><article className="admin-product" key={x.id}><img src={x.image} alt={x.name}/><div><span>{x.category}</span><h3>{x.name}</h3><b>{x.price}</b><p>{x.description}</p><button onClick={()=>setEdit(x)}><Save size={14}/> Edit</button><button className="danger" onClick={()=>save(items.filter(i=>i.id!==x.id))}><Trash2 size={14}/> Delete</button></div></article>)}</div></section>{edit&&<div className="modal"><div className="modal-card"><h2>Edit product</h2>{([["name","Product name"],["price","Price"],["image","Image URL"],["tag","Badge"],["description","Description"]] as const).map(([k,l])=><label key={k}>{l}<input value={edit[k]} onChange={e=>setEdit({...edit,[k]:e.target.value})}/></label>)}<label>Category<select value={edit.category} onChange={e=>setEdit({...edit,category:e.target.value})}>{cats.map(c=><option key={c}>{c}</option>)}</select></label><button onClick={()=>{save(items.some(i=>i.id===edit.id)?items.map(i=>i.id===edit.id?edit:i):[...items,edit]);setEdit(null)}}>Save product</button></div></div>}</main>}
